// <auto-generated />
using System;
using FileProcessingService.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FileProcessingService.Persistence.Migrations
{
    [DbContext(typeof(FileProcessingContext))]
    [Migration("20210901100717_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FileProcessingService.Domain.Entities.DuplicateWordStatistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DuplicateCount")
                        .HasColumnType("int");

                    b.Property<string>("DuplicateWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcessedFileContentId")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedFileContentId");

                    b.ToTable("DuplicateWordStatistics");
                });

            modelBuilder.Entity("FileProcessingService.Domain.Entities.ProcessedFileContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ElementName")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("ProcessedFileContents");
                });

            modelBuilder.Entity("FileProcessingService.Domain.Entities.DuplicateWordStatistic", b =>
                {
                    b.HasOne("FileProcessingService.Domain.Entities.ProcessedFileContent", "ProcessedFileContent")
                        .WithMany("DuplicateWordStatistics")
                        .HasForeignKey("ProcessedFileContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessedFileContent");
                });

            modelBuilder.Entity("FileProcessingService.Domain.Entities.ProcessedFileContent", b =>
                {
                    b.Navigation("DuplicateWordStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
